# Generated by Django 5.0.7 on 2024-07-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
