# Generated by Django 5.0.6 on 2024-07-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="option5",
            field=models.CharField(default="default", max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_option",
            field=models.CharField(default="default", max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option1",
            field=models.CharField(default="default", max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option2",
            field=models.CharField(default="default", max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option3",
            field=models.CharField(default="default", max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option4",
            field=models.CharField(default="default", max_length=200),
        ),
    ]
