# Generated by Django 5.0.6 on 2024-07-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0002_question_option5_alter_question_correct_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
    ]
