# Generated by Django 5.0.7 on 2024-08-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0003_examresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="num_noanswer",
            field=models.IntegerField(default=0),
        ),
    ]
