# Generated by Django 5.0.6 on 2024-07-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0003_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="comment",
            field=models.CharField(default="default", max_length=1000),
        ),
    ]
