# Generated by Django 5.0.6 on 2024-07-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0004_question_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="comment",
            field=models.TextField(default="default"),
        ),
    ]
