# Generated by Django 5.0.6 on 2024-07-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0005_alter_question_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="comment_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
    ]
