# Generated by Django 5.0.3 on 2025-01-12 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
