# Generated by Django 5.0.3 on 2025-08-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment_youtube_url',
            field=models.URLField(blank=True, help_text='해설용 유튜브 동영상 URL을 입력하세요', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='유튜브 동영상 URL을 입력하세요', null=True),
        ),
    ]
