# Generated by Django 5.0.3 on 2025-12-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_question_comment_youtube_url_question_youtube_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['display_order', 'date_created']},
        ),
        migrations.AddField(
            model_name='exam',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='표시 순서 (숫자가 작을수록 먼저 표시)'),
        ),
    ]
