# Generated by Django 5.0.3 on 2026-05-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_exam_options_exam_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_special',
            field=models.BooleanField(default=False, help_text='특별 승인된 사용자(is_specially_approved)에게만 표시'),
        ),
    ]
