# Generated by Django 5.2 on 2026-07-18 11:18

import anhub.storage_backends
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Journal Name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journal_covers/', verbose_name='Cover Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Volume')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Number')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='issue_covers/', verbose_name='Cover Image')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='journal.journal', verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('authors', models.CharField(blank=True, max_length=500, verbose_name='Authors')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI Summary')),
                ('pdf_file', models.FileField(blank=True, null=True, storage=anhub.storage_backends.PaperStorage(), upload_to='papers/', verbose_name='PDF File')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='journal.issue', verbose_name='Issue')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
                'ordering': ['order', '-created_date'],
            },
        ),
    ]
