# Generated by Django 5.2 on 2026-07-18 08:37

import anhub.storage_backends
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='학술지명')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='소개')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journal_covers/', verbose_name='표지 이미지')),
                ('is_active', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '학술지',
                'verbose_name_plural': '학술지',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='권(Volume)')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='호(Number)')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='발행일')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='issue_covers/', verbose_name='표지 이미지')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='journal.journal', verbose_name='학술지')),
            ],
            options={
                'verbose_name': '호',
                'verbose_name_plural': '호',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('authors', models.CharField(blank=True, max_length=500, verbose_name='저자')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI 요약')),
                ('pdf_file', models.FileField(blank=True, null=True, storage=anhub.storage_backends.PaperStorage(), upload_to='papers/', verbose_name='PDF 파일')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='journal.issue', verbose_name='호')),
            ],
            options={
                'verbose_name': '논문',
                'verbose_name_plural': '논문',
                'ordering': ['order', '-created_date'],
            },
        ),
    ]
