# Generated by Django 5.2 on 2026-07-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='short_summary',
            field=models.CharField(blank=True, help_text='One-line summary shown in the issue paper list.', max_length=300, verbose_name='Short Summary'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='Full multi-paragraph summary shown on the paper detail page.', verbose_name='AI Summary'),
        ),
    ]
