# Generated by Django 5.2 on 2026-07-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_paper_short_summary_alter_paper_ai_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='paper',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='paper_covers/', verbose_name='Cover Image'),
        ),
    ]
