# Generated by Django 5.2 on 2026-07-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_issue_cover_image_paper_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Issue Number'),
        ),
    ]
