# Generated by Django 5.2 on 2026-07-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_issue_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='journal',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text="Direct link to a cover image (e.g. from the journal's website). No upload needed.", verbose_name='Cover Image URL'),
        ),
        migrations.AddField(
            model_name='paper',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Direct link to a cover image. No upload needed.', verbose_name='Cover Image URL'),
        ),
    ]
