# Generated by Django 5.2.17 on 2026-09-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "journal",
            "0005_remove_journal_cover_image_remove_paper_cover_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="doi",
            field=models.CharField(blank=True, max_length=255, verbose_name="DOI"),
        ),
        migrations.AddField(
            model_name="paper",
            name="processing_message",
            field=models.TextField(blank=True, verbose_name="자동 처리 메시지"),
        ),
        migrations.AddField(
            model_name="paper",
            name="processing_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "완료/수동"),
                    ("pending", "대기"),
                    ("running", "처리 중"),
                    ("error", "오류"),
                ],
                default="",
                max_length=10,
                verbose_name="자동 처리 상태",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="processing_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="source_sha1",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="올린 PDF 의 지문 - 같은 파일을 두 번 올리지 않도록",
                max_length=40,
            ),
        ),
    ]
