services:
  - type: web
    name: anexus
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn anhub.wsgi --workers 2 --timeout 60
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
