# Generated by Django 5.0.7 on 2024-08-04 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="content",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="name",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="user1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="user2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms_joined",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
