# Generated by Django 5.0.7 on 2024-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="training_hospital",
            field=models.CharField(
                choices=[("서울대병원", "서울대병원"), ("기타", "기타")], default="기타", max_length=255
            ),
        ),
    ]
