# Generated by Django 5.0.7 on 2024-09-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_training_hospital"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_specially_approved",
            field=models.BooleanField(default=False),
        ),
    ]
