# Generated by Django 5.0.7 on 2024-09-14 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_is_specially_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_specially_approved",
        ),
    ]
