# Generated by Django 5.0.7 on 2024-09-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_customuser_is_specially_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_specially_approved",
            field=models.BooleanField(default=False),
        ),
    ]
