# Generated by Django 5.0.3 on 2025-12-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_training_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
