# Generated by Django 5.0.3 on 2025-01-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurgerySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room', models.CharField(max_length=10)),
                ('time_slot', models.CharField(max_length=10)),
                ('surgery_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=50)),
                ('surgeon', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_info', models.CharField(max_length=20)),
            ],
        ),
    ]
