# Generated by Django 5.0.3 on 2025-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryschedule',
            name='status',
            field=models.CharField(default='예정', max_length=50),
        ),
    ]
