# Generated by Django 5.0.3 on 2025-01-31 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_surgeryschedule_status'),
    ]

    operations = [
    ]
