# Generated by Django 5.0.3 on 2025-01-31 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_surgeryschedule_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='schedule.surgeryschedule')),
            ],
            options={
                'db_table': 'patient_memos',
            },
        ),
    ]
