# Generated by Django 5.2 on 2026-09-24 13:32

from django.db import migrations, models

FINISHED_STATUSES = {"완료", "종료", "수술완료", "퇴실", "회복", "회복실"}


def room_flags_to_cases(apps, schema_editor):
    """방 단위 당직/Hold 표시를 그 방의 끝나지 않은 수술들로 옮김."""
    RoomFlag = apps.get_model("schedule", "RoomFlag")
    SurgerySchedule = apps.get_model("schedule", "SurgerySchedule")
    for flag in RoomFlag.objects.all():
        cases = [c for c in SurgerySchedule.objects.filter(user_id=flag.user_id, room=flag.room)
                 if " ".join((c.status or "").split()) not in FINISHED_STATUSES]
        for case in cases:
            case.on_call = case.on_call or flag.on_call
            case.hold = case.hold or flag.hold
            case.save(update_fields=["on_call", "hold"])


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_anesthesiologist_roomflag"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgeryschedule",
            name="hold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surgeryschedule",
            name="on_call",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surgeryschedule",
            name="status_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(room_flags_to_cases, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="RoomFlag",
        ),
    ]
