# Generated by Django 5.2 on 2026-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0009_anesthesia_type_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgeryschedule",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="surgeryschedule",
            name="room_locked",
            field=models.BooleanField(default=False),
        ),
    ]
