# Generated by Django 5.2 on 2026-09-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0010_manual_room_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surgeryschedule",
            name="room_locked",
        ),
    ]
