# Generated by Django 5.2 on 2026-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0011_remove_room_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgeryschedule",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surgeryschedule",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
