# Generated by Django 5.2.17 on 2026-09-30 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def enable_rls(apps, schema_editor):
    # Supabase REST API 로 읽히지 않도록 (다른 테이블과 같은 규칙). 사이트는 RLS 를 우회하는 계정으로 접속.
    if schema_editor.connection.vendor == "postgresql":
        for table in ("schedule_dutystaff", "schedule_roomkeeper"):
            schema_editor.execute(f"alter table {table} enable row level security")


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0012_case_start_finish_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("user", "date", "name")},
            },
        ),
        migrations.CreateModel(
            name="RoomKeeper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("room", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_keepers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "unique_together": {("user", "date", "room", "name")},
            },
        ),
        migrations.RunPython(enable_rls, migrations.RunPython.noop),
    ]
