# Generated by Django 5.2.17 on 2026-10-01 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0013_room_keepers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dutystaff",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dutystaff",
            name="role",
            field=models.CharField(
                choices=[("keeper", "근무자"), ("anes", "마취의")],
                default="keeper",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dutystaff",
            unique_together={("user", "date", "role", "name")},
        ),
    ]
