# Generated by Django 5.2.17 on 2026-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0017_saved_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgeryschedule",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
