# Generated by Django 5.2.17 on 2026-09-27 09:16

from django.db import migrations, models


def enable_rls(apps, schema_editor):
    # Supabase REST API 로 읽히지 않도록 (다른 테이블과 같은 규칙). 사이트는 RLS 를 우회하는 계정으로 접속.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("alter table land_dailyvisit enable row level security")


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(enable_rls, migrations.RunPython.noop),
    ]
