# Generated by Django 5.0.7 on 2024-07-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drugName", models.CharField(default="default", max_length=100)),
                ("nx_hold_b_p", models.TextField(default="default")),
                ("nx_restart_a_p", models.TextField(default="default")),
                ("nx_hold_b_c", models.TextField(default="default")),
                ("nx_restart_a_c", models.TextField(default="default")),
                ("db_hold_b_p", models.TextField(default="default")),
                ("db_restart_a_p", models.TextField(default="default")),
                ("db_hold_b_c", models.TextField(default="default")),
                ("db_restart_a_c", models.TextField(default="default")),
                ("sp_hold_b_p", models.TextField(default="default")),
                ("sp_restart_a_p", models.TextField(default="default")),
                ("sp_hold_b_c", models.TextField(default="default")),
                ("sp_restart_a_c", models.TextField(default="default")),
                ("ap_hold_b_p", models.TextField(default="default")),
                ("ap_restart_a_p", models.TextField(default="default")),
                ("ap_hold_b_c", models.TextField(default="default")),
                ("ap_restart_a_c", models.TextField(default="default")),
            ],
        ),
    ]
