# Generated by Django 5.0.6 on 2024-06-23 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drugName", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Neuraxial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hold_b_p", models.TextField()),
                ("restart_a_p", models.TextField()),
                ("hold_b_c", models.TextField()),
                ("restart_a_c", models.TextField()),
                (
                    "coag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="coag.coag"
                    ),
                ),
            ],
        ),
    ]
