# Generated by Django 5.0.6 on 2024-06-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coag",
            name="ap_hold_b_c",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="ap_hold_b_p",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="ap_restart_a_c",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="ap_restart_a_p",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="db_hold_b_c",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="db_hold_b_p",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="db_restart_a_c",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="db_restart_a_p",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="nx_hold_b_c",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="nx_hold_b_p",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="nx_restart_a_c",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="nx_restart_a_p",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="sp_hold_b_c",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="sp_hold_b_p",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="sp_restart_a_c",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="coag",
            name="sp_restart_a_p",
            field=models.TextField(default="default"),
        ),
        migrations.AlterField(
            model_name="coag",
            name="drugName",
            field=models.CharField(default="default", max_length=100),
        ),
        migrations.DeleteModel(
            name="Neuraxial",
        ),
    ]
