# Generated by Django 5.0.7 on 2024-08-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coag",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
