# Generated by Django 5.0.6 on 2024-06-25 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="postname",
        ),
        migrations.AddField(
            model_name="board",
            name="author",
            field=models.CharField(default="default", max_length=10),
        ),
        migrations.AddField(
            model_name="board",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 25, 4, 29, 2, 125452, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="modified_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 25, 4, 29, 2, 125452, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="title",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AlterField(
            model_name="board",
            name="contents",
            field=models.TextField(default="default"),
        ),
    ]
