# Generated by Django 5.0.7 on 2024-07-28 07:22

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='contents',
            field=models.TextField(),  # 일시적으로 TextField로 변경
        ),
    ]