# Generated by Django 5.0.7 on 2024-07-28 07:22

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="contents",
            field=django_summernote.fields.SummernoteTextField(default="default"),
        ),
    ]
