# Generated by Django 5.0.7 on 2024-07-28 07:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_alter_board_contents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="contents",
            field=ckeditor.fields.RichTextField(default="default"),
        ),
    ]
