# Generated by Django 5.0.6 on 2024-06-25 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_remove_board_postname_board_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 25, 4, 29, 16, 724084, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="modified_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 25, 4, 29, 16, 724084, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
