# Generated by Django 5.0.6 on 2024-06-25 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_alter_board_created_date_alter_board_modified_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="board",
            name="modified_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
