# Generated by Django 5.0.6 on 2024-07-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_alter_board_created_date_alter_board_modified_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="author",
            field=models.CharField(default="default", max_length=500),
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(default="default", max_length=255),
        ),
    ]
