# Generated by Django 5.0.3 on 2025-09-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-is_notice', '-id']},
        ),
        migrations.AddField(
            model_name='board',
            name='is_notice',
            field=models.BooleanField(default=False, verbose_name='공지사항'),
        ),
    ]
