# Generated by Django 6.0.6 on 2026-06-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_contents_ckeditor5'),
        ('board', '0009_comment_parent'),
    ]

    operations = [
    ]
